import LegalPage, { generateLegalMetadata } from "@/components/legal-page";

export const metadata = generateLegalMetadata(
  "Website Disclaimer",
  "Important disclosures about the use of Portier AI's website and services."
);

export default function Page() {
  return (
    <LegalPage
      title="Website Disclaimer"
      description="Important disclosures about the use of Portier AI's website and services."
  lastUpdated="May 26, 2025"
    >
      ## General Disclaimer

The information provided on the Portier AI website is for general informational purposes only. While we strive to keep information accurate and current, we make no representations or warranties of any kind about the completeness, accuracy, reliability, or suitability of the information.

## No Professional Advice

Content on this website does not constitute professional business, legal, financial, or technical advice. You should consult appropriate professionals for advice specific to your situation before making business decisions.

## AI Output Disclaimer

AI-generated analyses, recommendations, and content provided through our website (including the AI Advisor chatbot and website analysis tool) are generated by artificial intelligence systems and:
- May not be 100% accurate or complete
- Should not be solely relied upon for critical business decisions
- Are provided as informational tools, not guarantees of results

## Results Disclaimer

Any case studies, testimonials, or performance metrics presented on this website represent specific client results. Individual results will vary based on numerous factors including industry, market conditions, implementation quality, and client engagement. We do not guarantee specific outcomes.

## Third-Party Links

Our website may contain links to third-party websites. We are not responsible for the content, accuracy, or practices of these external sites. The inclusion of links does not imply endorsement.

## Service Availability

Services described on this website are subject to availability and may change without notice. Specific service features and pricing are confirmed through direct engagement with our team, not solely through website content.

## Website Analysis Tool

Our website analysis tool provides automated assessments based on publicly available information. Results are intended as general guidance and may not capture all aspects of a website's performance, security, or compliance status.

## Contact

Portier AI  
Chicago, Illinois, USA  
Email: support@portierai.com
    </LegalPage>
  );
}
